# A base Docker image for Meteor applications. https://hub.docker.com/r/jshimko/meteor-launchpad/
FROM jshimko/meteor-launchpad:v1.1.1
ADD ../.meteor  opt/meteor/src/
MAINTAINER apinf <info@apinf.io>
